<script lang="ts">
  import { CablesPatch } from "../stores/stores";
  import { onMount } from "svelte";

  export let patch: string;

  let pathPatch: string = `/${patch}/patch.js`;

  const initializeCables = () => {
    CablesPatch.set(
      new CABLES.Patch({
        patch: CABLES.exportedPatch,
        prefixAssetPath: ``,
        assetPath: "",
        jsPath: pathPatch,
        glCanvasId: `cables_${patch}`,
        glCanvasResizeToWindow: true,
        onError: showError,
        onPatchLoaded: patchInitialized,
        onFinishedLoading: patchFinishedLoading,
        canvas: { alpha: true, premultipliedAlpha: true },
      })
    );
  };

  let currentID = 0;

  function showError(errId: any, errMsg: any) {
    // handle critical errors here if needed
    console.error("CRITICAL ERROR thrown from UI");
  }

  // Cables patch initialized, set up interop bindings
  // prepare for connecting patch vars to Elementary native

  function patchInitialized(patch: any) {
    console.log("patch initialized", CABLES);

    // get  all the variables from the Cables patch
    const cablesVariables = patch.getVars();
    console.log("cablesVariables", cablesVariables);
    // select only the variables with keys that start with the prefix "ui_"
    const uiVariables = Object.keys(cablesVariables).filter((key) =>
      key.startsWith("ui_")
    );

    // iterate over all the variables and set up generic event listeners
    // that will send the variable value to native plugin through
    // the requestParamValueUpdate function
    for (const key of uiVariables) {
      const value = cablesVariables[key];
      const paramId = key.replace("ui_", "");
      if (
        paramId !== "pickedID" &&
        paramId !== "readout" &&
        paramId !== "interpolatingPreset" &&
        paramId !== "paramsAverage"
      ) {
        value.on("change", function (newValue) {
          requestParamValueUpdate(paramId, newValue);
        });
      }
    }

    // special cases of variables that need to be handled differently
    const paramsAverage = patch.getVar("ui_paramsAverage");
    const pickedID = patch.getVar("pickedID");
    const readout = patch.getVar("readout");
    const interpolatingPreset = patch.getVar("ui_interpolatingPreset");

    // inerpolatingPreset is an array of all preset parameters
    // and is interpolated on the Cables side

    // extract the preset parameters from the array
    // and send them to native plugin
    // use the average as a change trigger

    if (paramsAverage) {
      paramsAverage.on("change", function (val) {
        const values = interpolatingPreset.getValue();
        if (values && values.length >= 4) {
          const params = ["decay", "mix", "mod", "size"];
          for (let i = 0; i < 4; i++) {
            if (values[i] !== undefined && params[i] !== undefined) {
              requestParamValueUpdate(params[i], values[i]);
            }
          }
        }
      });
    }

    // pickedID is the index of the preset that is currently being picked under the mouse
    // it needs to be divided by 2 because the preset index is 2->72
    // but actually there are only 36 presets
    if (pickedID) {
      pickedID.on("change", function (id) {
        const element = getConsoleDiv();
        clearInterval(currentTimer);
        element.style.opacity = 1;
        currentTimer = setInterval(() => {
          element.style.opacity = 0;
        }, 3000);
        // store it in a global variable
        currentID = id / 2;

        // log to the console inside the patch
        const stem = "‣ ";
        patch.setVariable("topLeftText", stem + "Node » " + currentID);
      });
    }

    // readout is the value generated by dragging the mouse over the circle
    // requestParamValueUpdate is called here with the circleID and the readout value
    if (readout) {
      readout.on("change", function (newValue) {
        const element = getConsoleDiv();
        element.classList.add("fadeIn");
        requestParamValueUpdate("circleID", currentID / 36);
        requestParamValueUpdate("nodeValue", newValue);
      });
    }
  }

  function patchFinishedLoading(patch) {
    // The patch is ready now, all assets have been loaded
    // not used so far
  }

  document.addEventListener("CABLES.jsLoaded", function (event) {
    CABLES.patch = new CABLES.Patch({
      patch: CABLES.exportedPatch,
      prefixAssetPath: "",
      assetPath: "assets/",
      jsPath: "",
      glCanvasId: "glcanvas",
      glCanvasResizeToWindow: true,
      onError: showError,
      onPatchLoaded: patchInitialized,
      onFinishedLoading: patchFinishedLoading,
      canvas: { alpha: true, premultipliedAlpha: true }, // make canvas transparent
    });
  });

  // Interop bindings
  function requestParamValueUpdate(paramId, value) {
    if (typeof globalThis.__postNativeMessage__ === "function") {
      globalThis.__postNativeMessage__("setParameterValue", {
        paramId,
        value,
      });
    }
  }
  onMount(() => {
    initializeCables();
  });
</script>

<canvas id="cables_{patch}" />
